### ISSUE TITLE
Lost connection to feed.adsbexchange.com

### ISSUE THREAD

**Issue by nick2k3** [mikenye/docker-adsbexchange#61]
Hi everyone, 
I am having trouble recently in reporting to ADSBExchange:

```
[mlat-client] Connected to multilateration server at feed.adsbexchange.com:31090, handshaking
[mlat-client] Lost connection to feed.adsbexchange.com:31090
[mlat-client] Reconnecting in 10.7 seconds
[mlat-client] Connected to multilateration server at feed.adsbexchange.com:64590, handshaking
[mlat-client] Lost connection to feed.adsbexchange.com:64590
[mlat-client] Reconnecting in 14.9 seconds
```

I am running the latest docker image on a raspberrypi4
Here is my docker compose:

```
adsbexchange:
    image: mikenye/adsbexchange
    tty: true
    container_name: adsbx
    restart: always
    environment:
      - BEASTHOST=readsb
      - TZ="Europe/Brussels"
      - LAT=y.yyyy
      - LONG=x.xxxx
      - ALT=21m
      - SITENAME=receiver_name
      - UUID=XXXXX-XXXXX-XXXXXX
    tmpfs:
      - /run:rw,nosuid,nodev,exec,relatime,size=64M,uid=1000,gid=1000

```

does anyone know how to diagnose this problem?
Thanks!
